name: CI CD Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build backend image
        run: |
          docker build -t myuser/student-api:latest backend
          docker push myuser/student-api:latest
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull myuser/student-api:latest
            docker stop student-api || true
            docker rm student-api || true
            docker run -d --name student-api -e DATABASE_URL='postgresql://postgres:postgres@localhost:5432/studentsdb' -p 8000:8000 myuser/student-api:latest
